### PR TITLE
Changes for 3.4.0

### PR DESCRIPTION
**Pull request by abakay**
* Switch from `BLAKE2b` to `BLAKE3` hash.
* Upgrade [clap](https://docs.rs/clap/) dependency to the next minor version `4.4.x`.
* Upgrade [toml](https://docs.rs/toml/) dependency to the next minor version `0.8.x`.

### CODE REVIEW

**Comment by burrbull** [comment]
`blake3` fails to compile on `apple-darwin`. See
https://github.com/rust-embedded/svd2rust/actions/runs/7306962730/job/19937683773?pr=789

**Comment by abakay** [comment]
I will take a look and maybe will make `blake3` conditional. But maybe the following could help as well: https://github.com/BLAKE3-team/BLAKE3/issues/180

**Comment by abakay** [comment]
> `blake3` fails to compile on `apple-darwin`. See https://github.com/rust-embedded/svd2rust/actions/runs/7306962730/job/19937683773?pr=789

Hi,

I ran the following commands in my environment and all of them successful:

`rustc 1.74.1 (a28077b28 2023-12-04)`

```sh
cargo check --target x86_64-apple-darwin --all-targets --all-features
cargo check --target x86_64-apple-darwin --all-targets --all-features --release

cargo clippy --target x86_64-apple-darwin --all-targets --all-features
cargo clippy --target x86_64-apple-darwin --all-targets --all-features --release
```

Please advise.

**Comment by burrbull** [comment]
have you tried to `build`?

**Comment by abakay** [comment]
> have you tried to `build`?

Yes I did:

```sh
cargo build --target x86_64-apple-darwin --all-targets --all-features
cargo build --target x86_64-apple-darwin --all-targets --all-features --release
```

**Comment by abakay** [comment]
> I will take a look and maybe will make `blake3` conditional. But maybe the following could help as well: [BLAKE3-team/BLAKE3#180](https://github.com/BLAKE3-team/BLAKE3/issues/180)

Did you see that post: https://github.com/BLAKE3-team/BLAKE3/issues/180

**Comment by abakay** [comment]
The hash could be set via crate features. Default type is `blake2b` #21

**Comment by abakay** [comment]
> `blake3` fails to compile on `apple-darwin`. See https://github.com/rust-embedded/svd2rust/actions/runs/7306962730/job/19937683773?pr=789

The hash could be set via crate features. Default type is blake2b (see #21)

**Pull request merged**
